apiVersion: v2
name: openarchiefbeheer
description: Opstellen, beheren en uitvoeren van vernietigingslijsten, voor gebruik met Zaakgericht werken

type: application
version: 1.3.7
appVersion: latest

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: maykin-utils-lib
    version: 0.1.0
    repository: https://maykinmedia.github.io/charts/
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami
    tags:
    - bitnami-common
