apiVersion: v2
name: openzaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 1.3.3
appVersion: 1.12.1

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
