apiVersion: v2
name: openzaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 1.13.1
appVersion: 1.26.0

dependencies:
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
