apiVersion: v2
name: maykin-cg-stack
description: Maykin Common Ground components

type: application
version: 0.0.3

dependencies:
  - name: openzaak
    version: 1.3.1
    repository: https://maykinmedia.github.io/charts/
    condition: openzaak.enabled

  - name: opennotificaties
    version: 1.3.0
    repository: https://maykinmedia.github.io/charts/
    condition: opennotificaties.enabled
