apiVersion: v2
name: openforms
description: Snel en eenvoudig slimme formulieren bouwen en publiceren

type: application
version: 1.8.10
appVersion: 3.0.1
icon: https://open-forms.readthedocs.io/en/stable/_static/logo.svg

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
