apiVersion: v2
name: openinwoner
description: Platform voor gemeenten en overheden om producten inzichtelijker en toegankelijker te maken voor inwoners.

type: application
version: 2.1.2
appVersion: 2.0.3

icon: https://docs.openinwoner.nl/en/latest/_static/logo.png

dependencies:
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: eck-operator
    version: 3.2.0
    repository: https://helm.elastic.co
    tags:
      - eck-operator.enabled
  - name: eck-elasticsearch
    version: 0.17.0
    repository: https://helm.elastic.co
    tags:
      - eck-elasticsearch.enabled
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
