apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbeheer.fullname" . }}
  labels:
    {{- include "openbeheer.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings.djangoSettingsModule | toString | quote }}
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  DB_HOST: {{ .Values.global.settings.databaseHost | default .Values.settings.database.host | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  USE_X_FORWARDED_HOST: {{ if .Values.settings.useXForwardedHost }}"True"{{ else }}"False"{{ end }}
  ENVIRONMENT: {{ .Values.settings.environment | default (include "openbeheer.fullname" .) }}
  ALLOWED_HOSTS: "{{ include "openbeheer.fullname" . }},{{ include "openbeheer.fullname" . }}.{{ .Release.Namespace }},{{ .Values.settings.allowedHosts | replace " " "" | toString }}"
  MYKN_API_URL: {{ printf "https://%s" .Values.settings.apiDomain }}
  MYKN_API_PATH: {{ .Values.settings.apiPath | toString | quote }}
  CSRF_TRUSTED_ORIGINS: {{ printf "https://%s" .Values.settings.apiDomain }}
  CSRF_COOKIE_SAMESITE: "Strict"
  CSRF_COOKIE_SECURE: "true"
  SESSION_COOKIE_SAMESITE: "Strict"
  SESSION_COOKIE_SECURE: "true"
  OPEN_ZAAK_ADMIN_BASE_URL: {{ .Values.settings.openzaakBaseUrl | toString | quote }}
  SESSION_COOKIE_AGE:  {{ .Values.settings.sessionCookieAge | toString | quote }}
  # IMPORTANT: This value must equal sessionCookieAge to prevent timeout mismatches
  OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS: {{ .Values.settings.sessionCookieAge | toString | quote }}
  {{- if .Values.tags.redis }}
  CACHE_DEFAULT: {{ printf "%s-master.%s:6379/0" (include "common.names.fullname" .Subcharts.redis) .Release.Namespace | toString | quote }}
  CACHE_AXES: {{ printf "%s-master.%s:6379/0" (include "common.names.fullname" .Subcharts.redis) .Release.Namespace | toString | quote }}
  {{ else }}
  CACHE_DEFAULT: {{ .Values.settings.cache.default | toString | quote }}
  CACHE_AXES: {{ .Values.settings.cache.axes | toString | quote }}
  {{- end }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  EMAIL_HOST: {{ .Values.settings.email.host | toString | quote }}
  EMAIL_PORT: {{ .Values.settings.email.port | toString | quote }}
  {{- if .Values.settings.email.username }}
  EMAIL_HOST_USER: {{ .Values.settings.email.username | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.useTLS }}
  EMAIL_USE_TLS: "True"
  {{- end }}
  {{- if .Values.settings.email.defaultFrom }}
  DEFAULT_FROM_EMAIL: {{ .Values.settings.email.defaultFrom | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVICE_NAME: {{ .Values.settings.elasticapm.serviceName | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.master }}
  UWSGI_MASTER:  {{ if .Values.settings.uwsgi.master }}"1"{{ else }}"0"{{ end }}
  {{- end }}
  {{- if .Values.settings.uwsgi.threads }}
  UWSGI_THREADS: {{ .Values.settings.uwsgi.threads  | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.processes }}
  UWSGI_PROCESSES: {{ .Values.settings.uwsgi.processes | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.maxRequests }}
  UWSGI_MAX_REQUESTS: {{ .Values.settings.uwsgi.maxRequests | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.harakiri }}
  UWSGI_HARAKIRI: {{ .Values.settings.uwsgi.harakiri | toString | quote }}
  {{- end }}
  {{- if .Values.settings.throttling.enable }}
  ENABLE_THROTTLING: "{{ .Values.settings.throttling.enable }}"
  {{- end }}
    {{- if .Values.settings.throttling.rateAnonymous }}
  THROTTLE_RATE_ANON: "{{ .Values.settings.throttling.rateAnonymous }}"
  {{- end }}
    {{- if .Values.settings.throttling.rateUser }}
  THROTTLE_RATE_USER: "{{ .Values.settings.throttling.rateUser }}"
  {{- end }}
  {{ if .Values.settings.debug }}
  DEBUG: "True"
  {{- end }}
  {{ if .Values.settings.disable2fa }}
  DISABLE_2FA: "True"
  {{- end }}
  IS_HTTPS: {{ if .Values.settings.isHttps }}"True"{{ else }}"False"{{ end }}
