{{- if and .Values.existingSecret .Values.azureVaultSecret.vaultName }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "openforms.fullname" . }}-akv2k8s
spec:
  vault:
    name: {{ .Values.azureVaultSecret.vaultName | toString | quote }}
    object:
      contentType: {{ .Values.azureVaultSecret.contentType | toString | quote }}
      name: {{ .Values.azureVaultSecret.objectName | toString | quote }}
      type: multi-key-value-secret
  output:
    secret:
      name: {{ .Values.existingSecret }}
{{- end }}     