apiVersion: v2
name: objecten
description: API om objecten te beheren die behoren bij een bepaald objecttype

type: application
version: 2.3.1
appVersion: 2.3.1

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
