apiVersion: v2
name: opennotificaties
description: API voor het routeren van notificaties

type: application
version: 1.9.5
appVersion: 1.9.0

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: rabbitmq
    version: 11.7.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
