apiVersion: v2
name: objecttypen
description: API om object definities te beheren

type: application
version: 1.1.0
appVersion: 2.2.0

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
