apiVersion: v2
name: icatt-odpc
description: A helm chart for the ICATT Openbaar-Documenten-Publicatie-Component

type: application

# Chart version 
version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
