{{ if and .Values.global.configuration.enabled .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opennotificaties.fullname" . }}-configuration
  labels:
    {{- include "opennotificaties.labels" . | nindent 4 }}
data:
  configuration.yaml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.configuration.data "context" $) | nindent 4 }}
{{- end }}